### PR TITLE
Linting run

### PR DESCRIPTION
**Pull request by unquietwiki**
@R-T-B we were talking about the fixes on the main Kopernicus mod. I had applied the same strategy here yesterday; but honestly not sure much actually changed aside from matching the format & BindingFlag order changes the one linter that applied found.

### CODE REVIEW

**Comment by R-T-B** [comment]
I'll gladly save this for a rainy day, but not going to merge it just yet as the config-parser is not a performance intensive part of the code.  Probably will merge it with next needed change here, which may be a while.

**Comment by unquietwiki** [comment]
@R-T-B yeah, no biggie on this.

**Comment by democat3457** [comment]
imo having a space in the cast helps make it more readable than without

**Comment by unquietwiki** [comment]
@democat3457 I've been trying to match a consistent format across the various projects I've been investigating. Space-after-comma & wrapped long-lines have been fine; folks seem mixed on reducing things to lambdas / arrow functions. I had one dev gnaw into me about Unity nulls; now that I'm checking for that, I'm finding & patching quite a few of those calls. LINQ, I'm not an expert at; really just use what VS suggests, else it's 50-50 on working or slowing things down. One other thing: **.ForEach** when there isn't a yield return involved; that gets rid of some redundancies.

**Comment by R-T-B** [comment]
I haven't actually established a repo-wide formatting policy.  May be worth doing.

I usually just format things like I'd do for a personal project, which as you can see, is a mix of a few things.  As far as long lines, I usually leave them long and don't worry about it (I have a 4K monitor) but am open to discussion as that won't affect performance either way.

**Comment by democat3457** [comment]
> @democat3457 I've been trying to match a consistent format across the various projects I've been investigating. Space-after-comma & wrapped long-lines have been fine; folks seem mixed on reducing things to lambdas / arrow functions. I had one dev gnaw into me about Unity nulls; now that I'm checking for that, I'm finding & patching quite a few of those calls.

Interesting...

**Pull request closed without merging**
